// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzmjxxxtiplwdkhvbzjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6bWp4eHh0aXBsd2RraHZiempzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNjc4NDUsImV4cCI6MjA2Njk0Mzg0NX0.rOTGD-jaI7lhYsNodrzMSrf89vwdUTLO6heQILq___4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});